# Dados de treino e validação convertidos para o formato IOB2,
# pronto para ser usado pelo tokenizador e pelo Trainer da Hugging Face.

DADOS_DE_TREINO_IOB = [
    {'tokens': ['Eu', 'presto', 'atenção', 'no', 'que', 'eles', 'dizem'], 'ner_tags_str': ['O', 'B-ACT', 'I-ACT', 'O', 'O', 'O', 'B-ACT']},
    {'tokens': ['Fidel', 'e', 'Pinochet', 'tiram', 'sarro', 'de', 'você'], 'ner_tags_str': ['B-PER', 'O', 'B-PER', 'B-ACT', 'I-ACT', 'O', 'O']},
    {'tokens': ['Que', 'não', 'faz', 'nada'], 'ner_tags_str': ['O', 'O', 'B-ACT', 'O']},
    {'tokens': ['Você', 'que', 'ama', 'o', 'que', 'faz'], 'ner_tags_str': ['O', 'O', 'B-ACT', 'O', 'O', 'B-ACT']},
    {'tokens': ['E', 'não', 'faz', 'o', 'que', 'ama'], 'ner_tags_str': ['O', 'O', 'B-ACT', 'O', 'O', 'B-ACT']},
    {'tokens': ['Falta', ',', 'em', 'um', 'domingo', 'azul', ','], 'ner_tags_str': ['O', 'O', 'O', 'O', 'B-TEMP', 'O', 'O']},
    {'tokens': ['No', 'jornal', ',', 'da', 'capital'], 'ner_tags_str': ['O', 'B-MIDIA', 'O', 'O', 'O']},
    {'tokens': ['Um', 'dia', 'desses', ',', 'eu', 'vou', 'me', 'embora'], 'ner_tags_str': ['B-TEMP', 'I-TEMP', 'O', 'O', 'O', 'B-ACT', 'I-ACT', 'I-ACT']},
    {'tokens': ['Um', 'dia', 'desses', ',', 'eu', 'caio', 'fora'], 'ner_tags_str': ['B-TEMP', 'I-TEMP', 'O', 'O', 'O', 'B-ACT', 'I-ACT']},
    {'tokens': ['Eu', "'to", 'vivendo', ',', 'eu', "'to", 'esperando'], 'ner_tags_str': ['O', 'O', 'B-ACT', 'O', 'O', 'O', 'B-ACT']},
    {'tokens': ['Eu', "'to", 'cansado', 'de', 'esperar'], 'ner_tags_str': ['O', 'O', 'O', 'O', 'B-ACT']},
    {'tokens': ['Onde', 'a', 'vida', 'corre', 'pra', 'trás'], 'ner_tags_str': ['O', 'O', 'O', 'B-ACT', 'O', 'O']},
    {'tokens': ['Tentando', 'justificar', 'o', 'injustificável'], 'ner_tags_str': ['O', 'B-ACT', 'O', 'O']},
    {'tokens': ['Defendendo', 'o', 'seu', 'quintal'], 'ner_tags_str': ['B-ACT', 'O', 'O', 'O']},
    {'tokens': ['E', 'eu', 'que', 'não', 'fumo', ',', 'bebi', 'o', 'copo', 'de', 'conhaque'], 'ner_tags_str': ['O', 'O', 'O', 'O', 'O', 'O', 'B-ACT', 'O', 'O', 'O', 'B-PRODUTO']},
    {'tokens': ['Eu', 'que', 'não', 'bebo', ',', 'pedi', 'um', 'cigarro'], 'ner_tags_str': ['O', 'O', 'O', 'O', 'O', 'B-ACT', 'O', 'B-PRODUTO']},
    {'tokens': ['Mas', 'o', 'dândi', 'me', 'disse', ':', "'Rapaz", '...'], 'ner_tags_str': ['O', 'O', 'O', 'O', 'B-ACT', 'O', 'O', 'O']},
    {'tokens': ['Você', 'me', 'faz', 'correr', 'demais'], 'ner_tags_str': ['O', 'O', 'O', 'B-ACT', 'O']},
    {'tokens': ['sabe', 'exatamente', 'onde', 'vai', 'parar'], 'ner_tags_str': ['O', 'O', 'O', 'O', 'B-ACT']},
    {'tokens': ['Nós', 'só', 'precisamos', 'ir'], 'ner_tags_str': ['O', 'O', 'O', 'B-ACT']},
    {'tokens': ['Nós', 'só', 'queremos', 'viver'], 'ner_tags_str': ['O', 'O', 'O', 'B-ACT']},
    {'tokens': ['Quando', 'eu', 'vivia', 'e', 'morria', 'na', 'cidade'], 'ner_tags_str': ['O', 'O', 'B-ACT', 'O', 'B-ACT', 'O', 'O']},
    {'tokens': ['E', 'à', 'noite', 'eu', 'acordava', 'banhado', 'em', 'suor'], 'ner_tags_str': ['O', 'O', 'B-TEMP', 'O', 'B-ACT', 'O', 'O', 'O']},
    {'tokens': ['Não', 'queremos', 'lembrar', 'o', 'que', 'esquecemos'], 'ner_tags_str': ['O', 'O', 'B-ACT', 'O', 'O', 'O']},
    {'tokens': ['Um', 'chiclete', 'de', 'menta'], 'ner_tags_str': ['O', 'B-PRODUTO', 'I-PRODUTO', 'I-PRODUTO']},
    {'tokens': ['Em', 'Porto', 'Alegre', 'ou', 'em', 'Belém'], 'ner_tags_str': ['O', 'B-LOC', 'I-LOC', 'O', 'O', 'B-LOC']},
    {'tokens': ['me', 'ajuda', ',', 'James', 'Dean'], 'ner_tags_str': ['O', 'B-ACT', 'O', 'B-PER', 'I-PER']},
    {'tokens': ['um', 'cassete', 'no', 'rádio'], 'ner_tags_str': ['O', 'B-PRODUTO', 'O', 'B-MIDIA']},
    {'tokens': ['Eu', 'tenho', 'uma', 'guitarra', 'elétrica'], 'ner_tags_str': ['O', 'O', 'O', 'B-PRODUTO', 'I-PRODUTO']},
    {'tokens': ['Antigamente', 'eu', 'sabia', 'exatamente', 'o', 'que', 'fazer'], 'ner_tags_str': ['B-TEMP', 'O', 'O', 'O', 'O', 'O', 'O']},
    {'tokens': ['Tem', 'uns', 'amigos', 'tocando', 'comigo'], 'ner_tags_str': ['O', 'O', 'O', 'B-ACT', 'O']},
    {'tokens': ['A', 'juventude', 'é', 'uma', 'banda', 'numa', 'propaganda', 'de', 'refrigerantes'], 'ner_tags_str': ['O', 'O', 'O', 'O', 'O', 'O', 'B-MIDIA', 'O', 'B-PRODUTO']},
    {'tokens': ['As', 'revistas', ',', 'as', 'revoltas', ',', 'as', 'conquistas', 'da', 'juventude'], 'ner_tags_str': ['O', 'B-MIDIA', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O']},
    {'tokens': ['Não', 'vim', 'até', 'aqui', 'pra', 'desistir', 'agora'], 'ner_tags_str': ['O', 'B-ACT', 'O', 'O', 'O', 'B-ACT', 'B-TEMP']},
    {'tokens': ['Entendo', 'você', ',', 'se', 'você', 'quiser', 'ir', 'embora'], 'ner_tags_str': ['B-ACT', 'O', 'O', 'O', 'O', 'O', 'B-ACT', 'I-ACT']},
    {'tokens': ['nas', 'últimas', '24', 'horas'], 'ner_tags_str': ['O', 'O', 'B-TEMP', 'I-TEMP']},
    {'tokens': ['Se', 'depender', 'de', 'mim', ',', 'eu', 'vou', 'até', 'o', 'fim'], 'ner_tags_str': ['O', 'O', 'O', 'O', 'O', 'O', 'B-ACT', 'O', 'O', 'O']},
    {'tokens': ['Um', 'dia', 'me', 'disseram'], 'ner_tags_str': ['B-TEMP', 'I-TEMP', 'O', 'B-ACT']},
    {'tokens': ['Que', 'os', 'ventos', 'às', 'vezes', 'erram', 'a', 'direção'], 'ner_tags_str': ['O', 'O', 'O', 'O', 'O', 'B-ACT', 'O', 'O']},
    {'tokens': ['A', 'chave', 'que', 'abre', 'todas', 'as', 'portas'], 'ner_tags_str': ['O', 'O', 'O', 'B-ACT', 'O', 'O', 'O']},
    {'tokens': ['Mas', 'a', 'verdade', 'também', ',', 'às', 'vezes', ',', 'cura'], 'ner_tags_str': ['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-ACT']},
    {'tokens': ['Um', 'beijo', 'de', 'cinema', ',', 'um', 'amor', 'de', 'almanaque'], 'ner_tags_str': ['O', 'O', 'O', 'B-MIDIA', 'O', 'O', 'O', 'O', 'B-MIDIA']},
    {'tokens': ['Eu', 'que', 'sempre', 'sonhei', 'em', 'ter', 'um', 'Mustang-68'], 'ner_tags_str': ['O', 'O', 'B-TEMP', 'B-ACT', 'O', 'O', 'O', 'B-PRODUTO']},
    {'tokens': ['fazendo', 'cenas', 'de', 'um', 'filme', 'de', 'amor', 'sem', 'fim'], 'ner_tags_str': ['B-ACT', 'O', 'O', 'O', 'B-MIDIA', 'O', 'O', 'O', 'O']},
    {'tokens': ['Hoje', ',', 'eu', 'confesso', ',', 'meu', 'bem', ',', 'eu', 'confesso'], 'ner_tags_str': ['B-TEMP', 'O', 'O', 'B-ACT', 'O', 'O', 'O', 'O', 'O', 'B-ACT']},
    {'tokens': ['um', 'refrão', 'pra', 'dizer', 'o', 'que', 'eu', 'sinto'], 'ner_tags_str': ['O', 'O', 'O', 'B-ACT', 'O', 'O', 'O', 'O']},
    {'tokens': ['Todo', 'mundo', 'tá', 'relendo', 'o', 'que', 'nunca', 'foi', 'lido'], 'ner_tags_str': ['O', 'O', 'O', 'B-ACT', 'O', 'O', 'O', 'O', 'O']},
    {'tokens': ['Todo', 'mundo', 'tá', 'comprando', 'os', 'mais', 'vendidos'], 'ner_tags_str': ['O', 'O', 'O', 'B-ACT', 'O', 'O', 'O']},
    {'tokens': ['O', 'Papa', 'levou', 'um', 'tiro', 'à', 'queima', 'roupa'], 'ner_tags_str': ['O', 'O', 'B-ACT', 'I-ACT', 'I-ACT', 'O', 'O', 'O']},
    {'tokens': ['Tá', 'na', 'cara', ',', 'tá', 'na', 'capa', 'da', 'revista'], 'ner_tags_str': ['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-MIDIA']},
    {'tokens': ['Os', 'óculos', 'do', 'John', 'ou', 'o', 'olhar', 'do', 'Paul', '?'], 'ner_tags_str': ['O', 'O', 'O', 'B-PER', 'O', 'O', 'O', 'O', 'B-PER', 'O']},
    {'tokens': ['Era', 'um', 'garoto', 'que', ',', 'como', 'eu', ',', 'amava', 'os', 'Beatles', 'e', 'os', 'Rolling', 'Stones'], 'ner_tags_str': ['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-ACT', 'O', 'O', 'O', 'O', 'O', 'O']},
    {'tokens': ['Girava', 'o', 'mundo', ',', 'mas', 'o', 'mundo', 'não', 'lhe', 'era', 'nada', 'demais'], 'ner_tags_str': ['B-ACT', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O']},
    {'tokens': ['Cantava', 'as', 'canções', 'que', 'eu', 'cantava'], 'ner_tags_str': ['B-ACT', 'O', 'O', 'O', 'O', 'O']},
    {'tokens': ['Mas', 'um', 'amigo', 'me', 'falou', 'que', 'ele', 'está', 'vivendo', 'em', 'paz'], 'ner_tags_str': ['O', 'O', 'O', 'O', 'B-ACT', 'O', 'O', 'O', 'B-ACT', 'O', 'O']},
    {'tokens': ['Fazendo', 'rock', ',', 'o', 'que', 'sempre', 'quis', 'fazer'], 'ner_tags_str': ['B-ACT', 'O', 'O', 'O', 'O', 'O', 'O', 'B-ACT']},
    {'tokens': ['Na', 'correnteza', 'do', 'rio', ',', 'eu', ',', 'um', 'peixe', 'a', 'nadar'], 'ner_tags_str': ['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-ACT']},
    {'tokens': ['No', 'meio', 'da', 'multidão', ',', 'ando', 'só'], 'ner_tags_str': ['O', 'O', 'O', 'O', 'O', 'B-ACT', 'O']},
    {'tokens': ['Ando', 'só', ',', 'como', 'um', 'pássaro', 'voando', 'em', 'pleno', 'ar'], 'ner_tags_str': ['B-ACT', 'O', 'O', 'O', 'O', 'O', 'B-ACT', 'O', 'O', 'O']},
    {'tokens': ['Ando', 'só', ',', 'como', 'um', 'barco', 'navegando', 'em', 'alto', 'mar'], 'ner_tags_str': ['B-ACT', 'O', 'O', 'O', 'O', 'O', 'B-ACT', 'O', 'O', 'O']},
    {'tokens': ['Ando', 'só', ',', 'não', 'sei', 'se', 'sei', 'voltar'], 'ner_tags_str': ['B-ACT', 'O', 'O', 'O', 'O', 'O', 'O', 'B-ACT']},
    {'tokens': ['O', 'nó', 'que', 'nos', 'une', ',', 'o', 'abismo', 'que', 'nos', 'separa'], 'ner_tags_str': ['O', 'O', 'O', 'O', 'B-ACT', 'O', 'O', 'O', 'O', 'O', 'B-ACT']},
    {'tokens': ['Eu', 'componho', ',', 'pra', 'não', 'chorar'], 'ner_tags_str': ['O', 'B-ACT', 'O', 'O', 'O', 'B-ACT']},
    {'tokens': ['Num', 'carro', 'de', 'aluguel', ',', 'sem', 'saber', 'pra', 'onde', 'ir'], 'ner_tags_str': ['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-ACT']},
    {'tokens': ['Procurando', 'abrigo', 'num', 'hotel', 'de', 'beira', 'de', 'estrada'], 'ner_tags_str': ['B-ACT', 'O', 'O', 'O', 'O', 'O', 'O', 'O']},
    {'tokens': ['Ela', 'para', 'e', 'fica', 'ali', 'parada'], 'ner_tags_str': ['O', 'B-ACT', 'O', 'B-ACT', 'O', 'O']},
    {'tokens': ['Olha', 'um', 'ponto', 'fixo', 'no', 'horizonte'], 'ner_tags_str': ['B-ACT', 'O', 'O', 'O', 'O', 'O']},
    {'tokens': ['Ela', 'abre', 'a', 'porta', 'do', 'seu', 'Opala'], 'ner_tags_str': ['O', 'B-ACT', 'O', 'O', 'O', 'O', 'B-PRODUTO']},
    {'tokens': ['Joga', 'a', 'chave', 'em', 'qualquer', 'canto'], 'ner_tags_str': ['B-ACT', 'O', 'O', 'O', 'O', 'O']},
    {'tokens': ['Deixa', 'a', 'porta', 'aberta'], 'ner_tags_str': ['B-ACT', 'O', 'O', 'O']},
    {'tokens': ['O', 'alarme', 'vai', 'soar'], 'ner_tags_str': ['O', 'O', 'O', 'B-ACT']},
    {'tokens': ['Que', 'ela', 'não', 'quer', 'mais', 'voltar'], 'ner_tags_str': ['O', 'O', 'O', 'O', 'O', 'B-ACT']},
    {'tokens': ['Girando', 'em', 'torno', 'de', 'si', 'mesma'], 'ner_tags_str': ['B-ACT', 'O', 'O', 'O', 'O', 'O']},
    {'tokens': ['Não', 'se', 'sinta', 'capaz', 'de', 'enganar'], 'ner_tags_str': ['O', 'O', 'O', 'O', 'O', 'B-ACT']},
    {'tokens': ['Por', 'ter', 'perdido', 'a', 'calma'], 'ner_tags_str': ['O', 'O', 'B-ACT', 'O', 'O']},
    {'tokens': ['Por', 'ter', 'vendido', 'a', 'alma', 'ao', 'diabo'], 'ner_tags_str': ['O', 'O', 'B-ACT', 'O', 'O', 'O', 'O']},
    {'tokens': ['Talvez', 'a', 'gente', 'se', 'encontre'], 'ner_tags_str': ['O', 'O', 'O', 'O', 'B-ACT']},
    {'tokens': ['Mais', 'um', 'dia', 'que', 'começa'], 'ner_tags_str': ['O', 'O', 'B-TEMP', 'O', 'B-ACT']},
    {'tokens': ['Vejo', 'a', 'vida', 'acontecer'], 'ner_tags_str': ['B-ACT', 'O', 'O', 'B-ACT']},
    {'tokens': ['Vejo', 'o', 'sol', 'que', 'me', 'aquece'], 'ner_tags_str': ['B-ACT', 'O', 'O', 'O', 'O', 'B-ACT']},
    {'tokens': ['E', 'eu', 'só', 'quero', 'te', 'encontrar'], 'ner_tags_str': ['O', 'O', 'O', 'O', 'O', 'B-ACT']},
    {'tokens': ['Subir', 'a', 'montanha', ',', 'ficar', 'sobre', 'as', 'nuvens'], 'ner_tags_str': ['B-ACT', 'O', 'O', 'O', 'B-ACT', 'O', 'O', 'O']},
    {'tokens': ['Apenas', 'apanhas-te', 'o', 'que', 'era', 'meu'], 'ner_tags_str': ['O', 'B-ACT', 'O', 'O', 'O', 'O']},
    {'tokens': ['E', 'tentas', 'me', 'vender'], 'ner_tags_str': ['O', 'B-ACT', 'O', 'B-ACT']},
    {'tokens': ['Amar', 'como', 'eu', 'amei'], 'ner_tags_str': ['B-ACT', 'O', 'O', 'B-ACT']},
    {'tokens': ['Sonhar', 'como', 'eu', 'sonhei'], 'ner_tags_str': ['B-ACT', 'O', 'O', 'B-ACT']},
    {'tokens': ['O', 'meu', 'pente-fino', ',', 'o', 'meu', 'violão'], 'ner_tags_str': ['O', 'O', 'O', 'O', 'O', 'O', 'B-PRODUTO']},
    {'tokens': ['O', 'meu', 'coração', 'que', 'bate', 'mais', 'forte', 'lá', 'fora'], 'ner_tags_str': ['O', 'O', 'O', 'O', 'B-ACT', 'O', 'O', 'O', 'O']},
    {'tokens': ['A', 'paisagem', 'que', 'não', 'se', 'move'], 'ner_tags_str': ['O', 'O', 'O', 'O', 'O', 'B-ACT']},
    {'tokens': ['Fico', 'esperando', 'você'], 'ner_tags_str': ['O', 'B-ACT', 'O']},
]

DADOS_DE_VALIDACAO_IOB = [
    {'tokens': ['Ela', 'não', 'precisa', 'de', 'ninguém', 'pra', 'dizer', 'o', 'que', 'fazer'], 'ner_tags_str': ['O', 'O', 'O', 'O', 'O', 'O', 'B-ACT', 'O', 'O', 'B-ACT']},
    {'tokens': ['Um', 'dia', ',', 'sem', 'saber', 'por', 'quê'], 'ner_tags_str': ['B-TEMP', 'I-TEMP', 'O', 'O', 'O', 'O', 'O']},
    {'tokens': ['Eu', 'saí', 'de', 'casa', ',', 'eu', 'saí', 'por', 'aí'], 'ner_tags_str': ['O', 'B-ACT', 'O', 'O', 'O', 'O', 'O', 'O', 'O']},
    {'tokens': ['Sem', 'pensar', 'em', 'voltar'], 'ner_tags_str': ['O', 'B-ACT', 'O', 'B-ACT']},
    {'tokens': ['Lutando', 'contra', 'moinhos', 'de', 'vento'], 'ner_tags_str': ['B-ACT', 'O', 'O', 'O', 'O']},
    {'tokens': ['Não', 'há', 'mais', 'o', 'que', 'dizer'], 'ner_tags_str': ['O', 'O', 'O', 'O', 'O', 'B-ACT']},
    {'tokens': ['Não', 'há', 'mais', 'o', 'que', 'fazer'], 'ner_tags_str': ['O', 'O', 'O', 'O', 'O', 'B-ACT']},
    {'tokens': ['Nós', 'dançamos', 'no', 'campo', 'minado'], 'ner_tags_str': ['O', 'B-ACT', 'O', 'O', 'O']},
    {'tokens': ['E', 'não', 'há', 'mais', 'pra', 'onde', 'correr'], 'ner_tags_str': ['O', 'O', 'O', 'O', 'O', 'O', 'B-ACT']},
    {'tokens': ['A', 'vida', 'real', 'não', 'tem', 'trilha', 'sonora'], 'ner_tags_str': ['O', 'O', 'O', 'O', 'O', 'B-MIDIA', 'I-MIDIA']},
    {'tokens': ['A', 'vida', 'real', ',', 'a', 'gente', 'inventa'], 'ner_tags_str': ['O', 'O', 'O', 'O', 'O', 'O', 'B-ACT']},
    {'tokens': ['Na', 'vida', 'real', ',', 'a', 'gente', 'se', 'vira'], 'ner_tags_str': ['O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-ACT']},
    {'tokens': ['A', 'cada', 'dia', ',', 'a', 'cada', 'manhã'], 'ner_tags_str': ['O', 'O', 'B-TEMP', 'O', 'O', 'O', 'B-TEMP']},
]